version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: inboxbrain-mysql
    environment:
      - MYSQL_DATABASE=inboxbrain
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build: ./services/app
    container_name: inboxbrain-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_DSN=${DB_DSN}
      - API_TOKEN=${API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - IMAP_MAILBOX=${IMAP_MAILBOX}
      - PROVIDER_LABEL=${PROVIDER_LABEL}
      - MAILBOX_LABEL=${MAILBOX_LABEL}
      - ENABLE_IMAP_IDLE=${ENABLE_IMAP_IDLE}
      - IMAP_IDLE_TIMEOUT=${IMAP_IDLE_TIMEOUT}
      - INGEST_SLEEP=${INGEST_SLEEP}
      - WORKER_SLEEP=${WORKER_SLEEP}
      - FIRST_RUN_BATCH=${FIRST_RUN_BATCH}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    container_name: inboxbrain-frontend
    depends_on:
      - app
      - mysql
    environment:
      - API_BASE=http://app:8000
      - API_TOKEN=${API_TOKEN}
      - DB_DSN=${DB_DSN}
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  dbdata:
